#travis configuration for coverage testing
language: c

#sudo: false # only for faster builds

install:
- cd ${TRAVIS_BUILD_DIR}

before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - gcc -g -o cello cello.c


after_success:
- cd ${TRAVIS_BUILD_DIR}
- echo "Success!!!"

